"""Add user

Revision ID: e94ab700d710
Revises: c630b3cd493e
Create Date: 2023-08-03 19:52:38.208336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94ab700d710'
down_revision = 'c630b3cd493e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('reaction',
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('like', 'dislike', name='reactiontype'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('publication_id', 'author_id')
    )
    op.add_column('publication', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'publication', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publication', type_='foreignkey')
    op.drop_column('publication', 'author_id')
    op.drop_table('reaction')
    op.drop_table('user')
    # ### end Alembic commands ###
